language: python
sudo: false
python:
- 2.7
- 3.5
- 3.6
install:
- pip install -e .
script: pytest tests
deploy:
  provider: pypi
  user: vmalloc
  password:
    secure: LB2D3QUQYomZ7yIwtTQSikuDNFrBLU9RFQ/9bwXxBiMBeMyrT4rpL5XOon8z0LvrsHlzmEAezf25qXmAqUO0LpsbhVXqAEcGfFrxGjOFZxl1eIj3HjK/8pBgR0VRiNYB/zbe/ll//4dy30qMqvRQJPnLKGOz3MkDbdZrdJDDKic=
  on:
    tags: true
    repo: getslash/confetti
    python: '3.6'
